language: python
sudo: required

services:
  - docker

before_install:
  - sudo pip install docker-compose

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec web pytest

after_script:
  - docker-compose down