version: "3.7"

services:
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mariadb/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todoListFastApi
    healthcheck:
      test: ["CMD","mysql --user=root --password=root --execute \"SHOW DATABASES;\""]
      interval: 3s
      timeout: 1s
      retries: 5
  web:
    build: .
    command:  ["./scripts/wait-for-db.sh", "--","uvicorn", "src.main:app", "--reload", "--workers 1", "--host 0.0.0.0", "--port 8080"]
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=mysql://root:root@db/todoListFastApi
    depends_on:
      - db
#        condition: service_started
volumes:
  mariadb_data:
