version: "3.7"

services:
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mariadb/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todoListFastApi
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=mysql://root:root@db/todoListFastApi
    depends_on:
      - db
#        condition: service_started
volumes:
  mariadb_data:
